### ISSUE TITLE
Interesting proposal!

### ISSUE THREAD

**Issue by worstpractice** [isiahmeadows/proposal-divisor-dependent-modulo#1]
Thanks for taking the time to write this up @isiahmeadows, I had no idea about those pitfalls with dividend-dependent modulo operations.

A quick question: I tried modeling your truth table of expected vs observed outcomes, replacing the example `isEven` and `isOdd` functions with the following logic:

```typescript
const isEven = (x: number): boolean => {
  return !(x & 1); // Casts to boolean and inverts the value.
};

const isOdd = (x: number): boolean => {
  return !!(x & 1); // Casts to boolean.
};
```

FWIW, this bitwise approach makes the aforementioned 'tests'  pass in all cases (read: the outcomes align with your truth table for the inputs you provided).

That being said, I'm convinced this approach has some pitfalls of its own, unbeknownst to me. Aside from the obviously ill-advised combination of bitwise operators and casts \**shudders\**.

For example, I know bitwise operations will truncate numbers down to 32 bits, but if I'm not mistaken, that should be fine purely for the purposes of checking oddness/evenness (AFAIK)... 🤔

Regardless, I couldn't imagine simply ANDing the dividend with 1 and casting the result to a boolean accomplishes 'everything you ask for'  in your proposal (save for: human-friendlyness, ergonomics, optimizability, and all that vital stuff)?

On that note: I saw you already mentioned the general concept of `x & 1` in your discussion, but I also noticed you didn't provide any bitwise ANDing version among your correct-but-unoptimizable `isOdd`/`isEven` implementations.

In short, why not? I suspect _some_ footgun or other in my implementation, but for the admittedly tiny batch of tests, it does seem to work. Since you clearly understand this better than me (thank goodness), I wonder — am I missing something here?

Great proposal anyhow, a `%%` operator sounds like a stroke of genius to me.

My full crappy throwaway code is [available here](https://www.typescriptlang.org/play?noImplicitReturns=false&noUncheckedIndexedAccess=true&useDefineForClassFields=true&allowUnusedLabels=true&declaration=false&importHelpers=true&target=99&jsx=0&ts=4.4.0-dev.20210525&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&strict=false&isolatedModules=false&noErrorTruncation=true#code/MYewdgziA2CmB0w4EMBOAKAlAbgFC9EgBcACASwgFEA3WMEgXhPQA8AuEsAVwFsAjWKkwc+IGLGT0GAPhIBvXCRKpYRLqnoBCViQBkJAIw4SAehMkAwsghEIJIiBKjxkkpIAm5MLVS37AC1gSamRoLgRcAF88AnAbcggAeXdPJlYObn5BYScxFClZBSUVNQ0STW0WPUNjM0trPwdclzB4KJjCeOsIQVI09mb8gBoSAE8RPIkwHOoQMlTCxXIAM2YqzQYmUcwA1BAAd05YQ8pUPYwcdvxO0iJYGzsmAG0lp4MR5dCegF0h14BmD5fWC-V4AJhGRFQ4VBSieABZIdCQX84QAGJEw1EkJ4AWgx9mRsJxuPeJE+0B+2LxgPJwOJeIhhKxr1xiOZKNeBngAFYgZTOXDcf9efyqbhvm47DcYssQKhmDccWBUCNYLQwGB7hBJSBVncHjsilKer50BQaHR0CrMGqNVqIBBLkpur1zUkUtahCNNOq6A6nTElJ1xPBoCAAOboAAGAAVuhwACRyRJ8ABWsGARHgFC9I3xOwA-CQAET4kskDKoSIJEjJv2a7UkYslhsVjglkApEuRaOXSJAA) (just press "Run" in the upper left corner).

All the best!

**Comment by dead-claudia** [comment]
I'll just put it this way: there's other moduli where this would be useful. (Think: 3, 10, etc.)

**Comment by dead-claudia** [comment]
2 was just for the sake of example.

**Comment by worstpractice** [comment]
> 2 was just for the sake of example.

\**smacks forehead*\* But of course. Why didn't I think of that?!

That's the tradeoff with examples I suppose — the mind has a way of mistaking the example for the proposal. Thanks @isiahmeadows.

**Comment by dead-claudia** [comment]
I'll go ahead and add a couple more examples to clarify.
