### ISSUE TITLE
README lists the -1 and -3 cases twice, with different answers

### ISSUE THREAD

**Issue by tabatkins** [isiahmeadows/proposal-divisor-dependent-modulo#2]
In the first table of "looks reasonable" results, -1 and -3 are among the inputs, and are listed as giving "correct" answers - `true` from `isOdd()` and `false` from `isEven()`.

But immediately below that they're called out specially and given different results - `false` from both functions.

I presume the first table just shouldn't list the negatives at all, since that's the confusing failure case devs might forget to test?

**Comment by dead-claudia** [comment]
Yeah, those numbers in particular shouldn't have been in the table. Fixed.

**Comment by dead-claudia** [comment]
Thanks for the catch, BTW!
